name: Block Merge Based on Time
description: You can prevent your members from merging pull requests during the specified time.
inputs:
  after:
    description: The time to start blocking merge. You can set exception time for specific days. For example, the value could be "17:30, 16:30 on Monday"
    required: false
    default: "00:00"
  before:
    description: The time to stop blocking merge. You can set exception time for specific days. For example, the value could be "09:00, 08:00 on Monday"
    required: false
    default: "00:00"
  timezone:
    description: Time zone to use
    required: true
  base-branches:
    description: The comma-separated base branches of pull requests. This tool will block only pull requests the base branches of which are listed in this parameter. You can set regular expressions surrounding with `/` like `/staging\/.*/` and just set string literals like `develop`. Also, the value `(default)` is acceptable, which means pull requests that will be merged into the default branch will be blocked. The default value is `/^.*$/` for backward compatibility.
    required: false
    default: "/^.*$/"
  prohibited-days-dates:
    description: The comma-separated days or dates to stop blocking merge for all day. You can also specify regional holidays with special syntax, such as "H:St. Barthélemy" and "BH:St. Barthélemy", which stand for "holidays of St. Barthélemy" and "before holidays of St. Barthélemy." The word after "H:" or "BH:" is a region name that is listed in `src/holidays.json` as a JSON key. For example, the value could be "Sunday, 2021-08-01, 2021-08-06/2021-08-10, H:Côte d’Ivoire"
    required: false
    default: ""
  no-block-label:
    description: The label to indicate the pull request should not be blocked
    required: false
    default: no-block
  commit-status-context:
    description: The commit status context
    required: false
    default: block-merge-based-on-time
  commit-status-description-with-success:
    description: The commit status description shown with success
    required: false
    default: The PR could be merged
  commit-status-description-while-blocking:
    description: The commit status description shown while blocking
    required: false
    default: The PR can't be merged based on time, which is due to your organization's policy
  commit-status-url:
    description: The commit status URL to describe why this action is conducted
    required: false
    default: ""
  token:
    description: The GitHub token used to create an authenticated client
    required: false
    default: ${{ github.token }}
outputs:
  pr-blocked:
    description: "A boolean value to indicate the pull reuqest is blocked. This is set only when the `pull_request` event occurs."
branding:
  icon: stop-circle
  color: yellow
runs:
  using: node20
  main: dist/index.js
